#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install other useful binaries
brew install aria2
brew install bash-completion
brew install git
brew install hub
brew install node
brew install rename
brew install ssh-copy-id
brew install sshrc
brew install wget
brew install z

# Remove outdated versions from the cellar
brew cleanup

# Check if the system is ready to brew
brew doctor
