#!/bin/bash

brew bundle --file=- <<RUBY
tap 'homebrew/cask'
tap 'homebrew/core'
tap 'homebrew/services'
brew 'aria2'
brew 'bat'
brew 'composer'
brew 'fish'
brew 'git'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnupg'
brew 'gpg-agent'
brew 'hub'
brew 'mas'
brew 'mysql@5.7'
brew 'node'
brew 'p7zip'
brew 'php'
brew 'pinentry-mac'
brew 'vim'
cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'atom'
cask 'beamer'
cask 'brave-browser'
cask 'couleurs'
cask 'flume'
cask 'github-desktop'
cask 'hyper'
cask 'imagealpha'
cask 'imageoptim'
cask 'qlstephen'
cask 'rectangle'
cask 'sequel-pro'
cask 'shifty'
cask 'signal'
cask 'sketch'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'transmit'
mas 'Dato', id: 1470584107
mas 'Lungo', id: 1263070803
mas 'Pixelmator Pro', id: 1289583905
mas 'Things', id: 904280696
RUBY
