#!/bin/bash

brew bundle --file=- <<RUBY
tap 'homebrew/cask-fonts'
tap 'homebrew/cask'
tap 'homebrew/core'
tap 'homebrew/services'
brew 'aria2'
brew 'bat'
brew 'composer'
brew 'dog'
brew 'fd'
brew 'fish'
brew 'gh'
brew 'git'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnupg'
brew 'gpg-agent'
brew 'mas'
brew 'mysql@5.7'
brew 'node'
brew 'p7zip'
brew 'php'
brew 'pinentry-mac'
brew 'vim'
cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'beamer'
cask 'brave-browser'
cask 'couleurs'
cask 'discord'
cask 'font-jetbrains-mono'
cask 'github-desktop'
cask 'imagealpha'
cask 'imageoptim'
cask 'rectangle'
cask 'signal'
cask 'spotify'
cask 'tableplus'
cask 'transmit'
cask 'visual-studio-code'
mas 'Dato', id: 1470584107
mas 'Glance', id: 1513574319
mas 'Lungo', id: 1263070803
mas 'Pixelmator Pro', id: 1289583905
mas 'Shareful', id: 1522267256
RUBY
