#!/usr/bin/env bash

npm install --global \
  @vinkla/alfred-emoji \
  alfred-kaomoji \
  alfred-npms \
  alfred-packagist \
  alfred-updater \
  autogit \
  browser-sync \
  empty-trash-cli \
  fast-cli \
  internal-ip-cli \
  npm-check-updates \
  public-ip-cli \
  title \
  trash-cli
