#!/usr/bin/env bash

npm install --global \
  npm \
  alfred-emoj \
  alfred-kaomoji \
  alfred-npms \
  alfred-packagist \
  empty-trash-cli \
  fast-cli \
  internal-ip-cli \
  npm-check-updates \
  public-ip-cli \
  title \
  trash-cli
