#!/usr/bin/env bash

nvm install stable
nvm alias default node

npm install --global \
  alfred-emoj \
  alfred-kaomoji \
  alfred-npms \
  alfred-packagist \
  alfred-updater \
  autogit \
  browser-sync \
  empty-trash-cli \
  fast-cli \
  internal-ip-cli \
  npm-check-updates \
  public-ip-cli \
  title \
  trash-cli
