#!/usr/bin/env bash

set -e

# shellcheck disable=SC2162
read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
echo
if [[ ${REPLY} =~ ^[Yy]$ ]]; then
  rsync -avh ./home/ "$HOME";
fi;
