#!/usr/bin/env bash

git pull origin master;

read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
echo
if [[ ${REPLY} =~ ^[Yy]$ ]]; then
  rsync -avh ./home/ ~;
  # shellcheck source="$HOME"/.bash_profile
	source ~/.bash_profile;
	chflags hidden ~/bin;
fi;
