#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade --all

# Install GNU `sed`, overwriting the built-in `sed`.
brew install gnu-sed --with-default-names

# Add more version of binaries
brew tap homebrew/versions

# Install Bash 4.
# Note: don’t forget to add `/usr/local/bin/bash` to `/etc/shells` before
# running `chsh`.
brew install bash
brew install bash-completion2

# Install never version of sqlite3 with math functions
brew install sqlite --with-functions

# Install other useful binaries
brew install aria2
brew install git
brew install hub
brew install node
brew install rename
brew install ssh-copy-id
brew install sshrc
brew install wget
brew install z

# Remove outdated versions from the cellar
brew cleanup

# Check if the system is ready to brew
brew doctor
