#!/bin/bash

# Make sure we’re using the latest NPM version
npm install -g npm@latest;

# Install useful npm packages
npm install -g gulp
npm install -g bower
npm install -g npm-check-updates
npm install -g grunt-cli
