#!/usr/bin/env bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade --all

# Install more recent versions of PHP
brew install homebrew/php/php56

# Install PHP package management binary
brew install homebrew/php/composer

# Remove outdated versions from the cellar
brew cleanup

# Check if the system is ready to brew
brew doctor
